.travis.yml
Also, set `sudo: false` to use new Travis infrastructure
See: http://docs.travis-ci.com/user/migrating-from-legacy/
=> Update .travis.yml to use 0.8, 0.10 and 0.12

.gitignore, .npmignore, .travis.yml, lib/referee-sinon.js, package.json, test/referee-sinon-test.js
Progress for https://github.com/busterjs/buster/issues/463
I'll wait for fully updated `buster-test` and `referee` to be on npm before I merge this.
=> Update deps, fix test runner, update error messages to use named params

.eslintrc.yaml, .travis.yml, README.md, docs/index.md, lib/referee-sinon.js, lib/referee-sinon.test.js, mkdocs.yml, package.json
Fixes #8 
This PR is aimed at ensuring that when using `referee-sinon` with modern Sinon, all the assertions from `sinon` are also available in `referee`.
It implements a test that verifies that all assertions on `sinon.assert` are also present on `referee.assert`.
Re-add `refereree.assert.callOrder` by stealing some code from Sinon (I mistakenly removed it in an earlier commit, that was merged as part of #7).
When using `sinon@4.4.2`, these assertions are missing:
* `callCount` (implemented in PR)
* ~`notCalled`~ (won't implement, this can be done with `refereree.refute.called`)
* `calledWithNew` (implemented in PR)
* `alwaysCalledWithNew` (implemented in PR)
* ~`neverCalledWith`~ (won't implement, this can be done with `refereree.refute.calledWith`)
* ~`neverCalledWithMatch`~ (won't …
=> Verify all sinon assertions mapped to referee

package.json
Used negate expressions in `package.json` files entry, although it goes
against recommendation below, because that's the only thing that
worked. Read the github references below for details.
> "The consequences are undefined" if you try to negate any of the files
> entries (that is, "!foo.js"). Please don't. Use .npmignore.
https://github.com/npm/npm/wiki/Files-and-Ignores#details
```text
.
├── LICENSE
├── README.md
├── docs
│   └── index.md
├── lib
│   └── referee-sinon.js
└── package.json
```
This uses [`tree`](https://en.wikipedia.org/wiki/Tree_(Unix)), on macOS install it using `brew install tree`
1. `npm install`
1. `npm pack`
1. Unpack the `sinonjs-referee-2.0.0.tgz` just created
1. `cd package`
1. `tree .`
1. Observe that you see the same as the example …
=> Add files directive to package.json to control what goes to npm

README.md, docs/index.md, lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
__BREAKING!__ This changes the API to expose the referee API with the applied sinon assertions and the sinon object. The `sinon` and the `@sinonjs/referee` modules have been changed to be actual dependencies.
~~__WORK IN PROGRESS DO NOT MERGE!__~~
This means that this module is a single dependency for people who want sinon and referee + the integrated assertions instead of requiring three modules.
This also means the require statement in test cases using this setup can be reduced to a single line:
```js
const { sinon, assert, refute } = require("@sinonjs/referee-sinon");
```
Open points:
Make sure to [review with whitespaces turned off](https://github.com/sinonjs/referee-sinon/pull/14/files?w=1).
=> Expose sinon and referee APIs

lib/referee-sinon.js, lib/referee-sinon.test.js
This allows to pass a call as the first argument to sinon assertions,
e.g. `assert.calledWith(spy.firstCall, 123)`. This is supported by Sinon
but wasn't working with this library because of the argument validateion
being too restrictive.
This change removes the `typeof "function"` check in `verifyFakes` and checks if the given argument supports `calledWith` instead of checking for `getCall`.
3. `npm t`
=> Support spy calls in assertions

lib/referee-sinon.js, package-lock.json, package.json
Fix #13
This PR replaces two functions that were duplicated from `sinon` with the same functions that have been extracted to `@sinonjs/commons`.
3. `npm test`
=> Import @sinonjs/commons

lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
This upgrades the two main dependencies to their latest majors. ~~For the build to succeed, [this need to be merged](https://github.com/sinonjs/referee/pull/84), a referee minor released and updated here.~~
2. ~~`npm ln @sinonjs/referee`~~
3. `npm install`
4. `npm t`
=> Referee v3 sinon v7

.eslintrc.yaml, lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json, rollup.config.js
This PR replaces https://github.com/sinonjs/referee-sinon/pull/39, and upgrades `eslint`, `eslint-config-sinon` and adds missing libraries and configs ... and fixes the new lint violations.
1. Observe that the linting passes!
=> Upgrade eslint

.gitignore, lib/referee-sinon.js
This PR slightly improves coverage.
I think this change should only be a patch version, as we haven't documented the previous behaviour anywhere, nor do we have any tests for it.
Reviewers are encouraged to read commit messages for explanation.
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    95.73 |    85.71 |    97.14 |    95.65 |                   |
referee-sinon.js |    95.73 |    85.71 |    97.14 |    95.65 | 23,62,144,317,318 |
------------------|----------|----------|----------|----------|-------------------|
```
``` …
```
=> Improve coverage

lib/referee-sinon.js, lib/referee-sinon.test.js
The code works fine in IE11, which is the only version of IE we care to support.
Removing this code helps move us towards 100% test coverage.
Setting `semver:major` because it will break things for IE8 users.
2. `npm ci`
3. `npm run test-cloud`
=> Remove IE8 workaround

lib/referee-sinon.test.js
This PR adds tests for ,which helps increase test coverage.
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    97.35 |    92.31 |    97.14 |    97.35 |                   |
referee-sinon.js |    97.35 |    92.31 |    97.14 |    97.35 |        69,315,316 |
------------------|----------|----------|----------|----------|-------------------|
```
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s | …
```
=> Add tests for calledOnceWithExactly

lib/referee-sinon.test.js, package-lock.json, package.json
Demonstrate that fake formatting isn't working as expected.
Fakes currently don't implement `printf` in sinon.
Maybe the `printf` implementation should move into `proxy.js`.
3. `npm t` currently fails
=> Add failing test for formatting fakes

lib/referee-sinon.test.js, package-lock.json, package.json
This demonstrates an issue that was discussed in sinonjs/sinon#2224. When using matchers created by one instance of samsam and using another instance of samsam to verify the matcher does not work.
Matchers are detected using `match.isMatcher(obj)` here: https://github.com/sinonjs/samsam/blob/d2df9c28610d5d9f78719a4fea4aacce1d2c84ac/lib/deep-equal.js#L73
This check fails to detect a matcher because it's checking the prototype chain:
https://github.com/sinonjs/samsam/blob/d2df9c28610d5d9f78719a4fea4aacce1d2c84ac/lib/create-matcher/is-matcher.js#L14-L16
However, the prototype instances of two versions of the same module are different.
We need to make sure we're not shipping different versions of samsam in one package. This test will help to detect if this is the case in the future.
1. Check …
=> Add failing test for issue with 2 samsam versions

lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
Upgrade referee to v6 and fix issues that where brought to the light by https://github.com/sinonjs/referee/pull/146.
Are we making this a major release in this project as well, since referee is re-exposed?
3. `npm test`
=> Referee v6

lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
Following up on https://github.com/sinonjs/referee/pull/183, this removes the dependency on `@sinonjs/formatio` and uses `util.inspect` for object stringification.
We want to get rid of `@sinonjs/formatio` in all Sinon projects and use `util.inspect` instead.
Since we released the mentioned PR as a patch which unfortunately breaks this module, we shouldn't release this change as a major. I would do a minor release.
3. `npm test`
Closes #97
=> Replace formatio with util inspect

.circleci/config.yml
This PR updates the CircleCI configuration to run tests in Node 14, replacing Node 13.
=> Run tests in node 14, instead of 13

.editorconfig, lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json, rollup.config.js
This PR upgrades `prettier` to latest and removes local configuration, adopting `prettier` default options.
**This breaks compatibility with IE11 and Edge Legacy, and is thus a `MAJOR` version release**
Also:
* upgrade `eslint-config-prettier`
* upgrade `eslint-plugin-prettier`
* run `prettier` on all JavaScript files
```sh
$(npm bin)/prettier -w -u .
```
We are exploring dropping IE11 and other legacy browsers. This PR demonstrates what the first step would look like.
* Upgrade `prettier`, `eslint-config-prettier` and `eslint-plugin-prettier` to latest
* Remove `.prettierrc`, accepting the default options
* Re-format all JavaScript files using `prettier`
* Configure editors via `.editorconfig`
1. `npm install`
1. `npm run lint`
1. Observe that there are no …
=> Upgrade prettier to 2.x

package-lock.json, package.json
This PR upgrades `@sinonjs/referee` to latest.
The two major versions of that are the same consequences as the last two major versions of this library, effectively dropping legacy runtimes.
=> Upgrade @sinonjs/referee to latest

lib/args-as-string.js, lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
This PR improves the messages from `calledOnceWith`, `calledOnceWithExactly` and `calledOnceWithMatch`.
The old message
```
[assert.calledOnceWith] Expected [Function (anonymous)] to be called once with arguments 1
```
Does not reveal whether the spy was called multiple times or with unexpected arguments
After this changset, there are two messages:
```
[assert.calledOnceWith] Expected [Function (anonymous)] to be called once, but was called 2 times
[assert.calledOnceWith] Expected [Function (anonymous)] to be called with arguments 2, but was called with 1
```
These messages clearly indicate which of the two combined expectations were unmet
0. Check out https://github.com/sinonjs/referee/pull/234
1. `npm link`
3. `npm link @sinonjs/referee`
4. Run …
=> Improve messages from calledOnceWith

.husky/pre-commit, lib/referee-sinon.js, lib/referee-sinon.test.js, package-lock.json, package.json
- Allow this package to be consume with `import '@sinonjs/referee-sinon'`
- Upgrade sinon to latest (v15)
- Upgrade referee to latest (v10)
- Make sure there is only one version of `@sinonjs/commons` and `@sinonjs/samsam` in the dependency tree.
Without explicitly exporting the `assert`, `refute`, `match` and `sinon` instances, consuming this package with `import` fails:
```
import { sinon } from '@sinonjs/referee-sinon';
^^^^^
SyntaxError: Named export 'sinon' not found. The requested module '@sinonjs/referee-sinon' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@sinonjs/referee-sinon';
const { sinon } = pkg;
at ModuleJob._instantiate …
```
=> Support module import and upgrade Sinon and Referee
